In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [12]:
iris = load_iris()

In [13]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

**LogisticRegression**

In [15]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_train,y_train)

1.0

**SVM**

In [16]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9555555555555556

**Random forest**

In [17]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9111111111111111

**Decision Tree**

In [20]:
model = tree.DecisionTreeClassifier()

In [21]:
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8888888888888888

In [22]:
from sklearn.model_selection import cross_val_score


**KFold cross validation**

**LogisticRegression using kfold Validation**

In [29]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target,cv=3)
l_scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [28]:
np.average(l_scores)

0.9733333333333333

**Decision tree using kfold Validation**

In [31]:
d_scores = cross_val_score(tree.DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [32]:
np.average(d_scores)

0.9533333333333334

**SVM using kfold Validation**

In [37]:
s_scores = cross_val_score(SVC(gamma='auto'), iris.data, iris.target)
s_scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [38]:
np.average(s_scores)

0.9800000000000001

**Random forest using kfold Validation**

In [40]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=30), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [41]:
np.average(r_scores)

0.9666666666666668